name: CI Pipeline
on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rulez linting..."

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - run: echo "Rulez testele..."

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Construiesc aplicația..."
